
# This file is automatically generated, you probably don't want to edit this

caOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "caOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            showSummary = TRUE,
            showSeriatedTable = FALSE,
            showInertia = TRUE,
            showDimDef = FALSE,
            showDimSummary = FALSE,
            showProfiles = FALSE,
            showCellContrib = FALSE,
            showCorrelations = FALSE,
            showInterpretation = FALSE,
            showSRDTable = FALSE,
            showSymmetricCoords = TRUE,
            showContribCoords = FALSE,
            showQualityContrib = TRUE,
            qualityThreshold = 0,
            residualThreshold = 1.96,
            distanceMetric = "pearson",
            residualType = "standardised",
            nAxes = 2,
            dim1 = 1,
            dim2 = 2,
            showSymmetricPlot = TRUE,
            symmetricShowClusters = FALSE,
            symmetricClusterTarget = "rows",
            symmetricShowContrib = "none",
            symmetricShowQuality = "none",
            symmetricShowPoints = "both",
            showGeometricPlot = FALSE,
            geometricRefVariable = "rows",
            geometricRefCategoryRow = NULL,
            geometricRefCategoryCol = NULL,
            showContribPlot = FALSE,
            contribFocus = "cols",
            contribShowClusters = FALSE,
            showQuality = FALSE,
            hideWeakContrib = FALSE,
            showScreePlot = FALSE,
            equalScale = TRUE,
            dotSize = 2.5,
            labelSize = 3.5,
            clusterAlpha = 0.05,
            showOverdispersionPlot = FALSE,
            showMethodInfo = FALSE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="ca",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=TRUE)
            private$..showSeriatedTable <- jmvcore::OptionBool$new(
                "showSeriatedTable",
                showSeriatedTable,
                default=FALSE)
            private$..showInertia <- jmvcore::OptionBool$new(
                "showInertia",
                showInertia,
                default=TRUE)
            private$..showDimDef <- jmvcore::OptionBool$new(
                "showDimDef",
                showDimDef,
                default=FALSE)
            private$..showDimSummary <- jmvcore::OptionBool$new(
                "showDimSummary",
                showDimSummary,
                default=FALSE)
            private$..showProfiles <- jmvcore::OptionBool$new(
                "showProfiles",
                showProfiles,
                default=FALSE)
            private$..showCellContrib <- jmvcore::OptionBool$new(
                "showCellContrib",
                showCellContrib,
                default=FALSE)
            private$..showCorrelations <- jmvcore::OptionBool$new(
                "showCorrelations",
                showCorrelations,
                default=FALSE)
            private$..showInterpretation <- jmvcore::OptionBool$new(
                "showInterpretation",
                showInterpretation,
                default=FALSE)
            private$..showSRDTable <- jmvcore::OptionBool$new(
                "showSRDTable",
                showSRDTable,
                default=FALSE)
            private$..showSymmetricCoords <- jmvcore::OptionBool$new(
                "showSymmetricCoords",
                showSymmetricCoords,
                default=TRUE)
            private$..showContribCoords <- jmvcore::OptionBool$new(
                "showContribCoords",
                showContribCoords,
                default=FALSE)
            private$..showQualityContrib <- jmvcore::OptionBool$new(
                "showQualityContrib",
                showQualityContrib,
                default=TRUE)
            private$..qualityThreshold <- jmvcore::OptionNumber$new(
                "qualityThreshold",
                qualityThreshold,
                min=0,
                max=1,
                default=0)
            private$..residualThreshold <- jmvcore::OptionNumber$new(
                "residualThreshold",
                residualThreshold,
                min=0,
                max=10,
                default=1.96)
            private$..distanceMetric <- jmvcore::OptionList$new(
                "distanceMetric",
                distanceMetric,
                options=list(
                    "pearson",
                    "freemanTukey"),
                default="pearson")
            private$..residualType <- jmvcore::OptionList$new(
                "residualType",
                residualType,
                options=list(
                    "standardised",
                    "adjusted"),
                default="standardised")
            private$..nAxes <- jmvcore::OptionInteger$new(
                "nAxes",
                nAxes,
                min=2,
                max=20,
                default=2)
            private$..dim1 <- jmvcore::OptionInteger$new(
                "dim1",
                dim1,
                min=1,
                max=20,
                default=1)
            private$..dim2 <- jmvcore::OptionInteger$new(
                "dim2",
                dim2,
                min=1,
                max=20,
                default=2)
            private$..showSymmetricPlot <- jmvcore::OptionBool$new(
                "showSymmetricPlot",
                showSymmetricPlot,
                default=TRUE)
            private$..symmetricShowClusters <- jmvcore::OptionBool$new(
                "symmetricShowClusters",
                symmetricShowClusters,
                default=FALSE)
            private$..symmetricClusterTarget <- jmvcore::OptionList$new(
                "symmetricClusterTarget",
                symmetricClusterTarget,
                options=list(
                    "rows",
                    "cols",
                    "both"),
                default="rows")
            private$..symmetricShowContrib <- jmvcore::OptionList$new(
                "symmetricShowContrib",
                symmetricShowContrib,
                options=list(
                    "none",
                    "rows",
                    "cols"),
                default="none")
            private$..symmetricShowQuality <- jmvcore::OptionList$new(
                "symmetricShowQuality",
                symmetricShowQuality,
                options=list(
                    "none",
                    "rows",
                    "cols",
                    "both"),
                default="none")
            private$..symmetricShowPoints <- jmvcore::OptionList$new(
                "symmetricShowPoints",
                symmetricShowPoints,
                options=list(
                    "both",
                    "rows",
                    "cols"),
                default="both")
            private$..showGeometricPlot <- jmvcore::OptionBool$new(
                "showGeometricPlot",
                showGeometricPlot,
                default=FALSE)
            private$..geometricRefVariable <- jmvcore::OptionList$new(
                "geometricRefVariable",
                geometricRefVariable,
                options=list(
                    "rows",
                    "cols"),
                default="rows")
            private$..geometricRefCategoryRow <- jmvcore::OptionLevel$new(
                "geometricRefCategoryRow",
                geometricRefCategoryRow,
                variable="(rows)")
            private$..geometricRefCategoryCol <- jmvcore::OptionLevel$new(
                "geometricRefCategoryCol",
                geometricRefCategoryCol,
                variable="(cols)")
            private$..showContribPlot <- jmvcore::OptionBool$new(
                "showContribPlot",
                showContribPlot,
                default=FALSE)
            private$..contribFocus <- jmvcore::OptionList$new(
                "contribFocus",
                contribFocus,
                options=list(
                    "cols",
                    "rows"),
                default="cols")
            private$..contribShowClusters <- jmvcore::OptionBool$new(
                "contribShowClusters",
                contribShowClusters,
                default=FALSE)
            private$..showQuality <- jmvcore::OptionBool$new(
                "showQuality",
                showQuality,
                default=FALSE)
            private$..hideWeakContrib <- jmvcore::OptionBool$new(
                "hideWeakContrib",
                hideWeakContrib,
                default=FALSE)
            private$..showScreePlot <- jmvcore::OptionBool$new(
                "showScreePlot",
                showScreePlot,
                default=FALSE)
            private$..equalScale <- jmvcore::OptionBool$new(
                "equalScale",
                equalScale,
                default=TRUE)
            private$..dotSize <- jmvcore::OptionNumber$new(
                "dotSize",
                dotSize,
                min=0.5,
                max=5,
                default=2.5)
            private$..labelSize <- jmvcore::OptionNumber$new(
                "labelSize",
                labelSize,
                min=1,
                max=8,
                default=3.5)
            private$..clusterAlpha <- jmvcore::OptionNumber$new(
                "clusterAlpha",
                clusterAlpha,
                min=0.01,
                max=0.5,
                default=0.05)
            private$..showOverdispersionPlot <- jmvcore::OptionBool$new(
                "showOverdispersionPlot",
                showOverdispersionPlot,
                default=FALSE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..showSeriatedTable)
            self$.addOption(private$..showInertia)
            self$.addOption(private$..showDimDef)
            self$.addOption(private$..showDimSummary)
            self$.addOption(private$..showProfiles)
            self$.addOption(private$..showCellContrib)
            self$.addOption(private$..showCorrelations)
            self$.addOption(private$..showInterpretation)
            self$.addOption(private$..showSRDTable)
            self$.addOption(private$..showSymmetricCoords)
            self$.addOption(private$..showContribCoords)
            self$.addOption(private$..showQualityContrib)
            self$.addOption(private$..qualityThreshold)
            self$.addOption(private$..residualThreshold)
            self$.addOption(private$..distanceMetric)
            self$.addOption(private$..residualType)
            self$.addOption(private$..nAxes)
            self$.addOption(private$..dim1)
            self$.addOption(private$..dim2)
            self$.addOption(private$..showSymmetricPlot)
            self$.addOption(private$..symmetricShowClusters)
            self$.addOption(private$..symmetricClusterTarget)
            self$.addOption(private$..symmetricShowContrib)
            self$.addOption(private$..symmetricShowQuality)
            self$.addOption(private$..symmetricShowPoints)
            self$.addOption(private$..showGeometricPlot)
            self$.addOption(private$..geometricRefVariable)
            self$.addOption(private$..geometricRefCategoryRow)
            self$.addOption(private$..geometricRefCategoryCol)
            self$.addOption(private$..showContribPlot)
            self$.addOption(private$..contribFocus)
            self$.addOption(private$..contribShowClusters)
            self$.addOption(private$..showQuality)
            self$.addOption(private$..hideWeakContrib)
            self$.addOption(private$..showScreePlot)
            self$.addOption(private$..equalScale)
            self$.addOption(private$..dotSize)
            self$.addOption(private$..labelSize)
            self$.addOption(private$..clusterAlpha)
            self$.addOption(private$..showOverdispersionPlot)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        showSummary = function() private$..showSummary$value,
        showSeriatedTable = function() private$..showSeriatedTable$value,
        showInertia = function() private$..showInertia$value,
        showDimDef = function() private$..showDimDef$value,
        showDimSummary = function() private$..showDimSummary$value,
        showProfiles = function() private$..showProfiles$value,
        showCellContrib = function() private$..showCellContrib$value,
        showCorrelations = function() private$..showCorrelations$value,
        showInterpretation = function() private$..showInterpretation$value,
        showSRDTable = function() private$..showSRDTable$value,
        showSymmetricCoords = function() private$..showSymmetricCoords$value,
        showContribCoords = function() private$..showContribCoords$value,
        showQualityContrib = function() private$..showQualityContrib$value,
        qualityThreshold = function() private$..qualityThreshold$value,
        residualThreshold = function() private$..residualThreshold$value,
        distanceMetric = function() private$..distanceMetric$value,
        residualType = function() private$..residualType$value,
        nAxes = function() private$..nAxes$value,
        dim1 = function() private$..dim1$value,
        dim2 = function() private$..dim2$value,
        showSymmetricPlot = function() private$..showSymmetricPlot$value,
        symmetricShowClusters = function() private$..symmetricShowClusters$value,
        symmetricClusterTarget = function() private$..symmetricClusterTarget$value,
        symmetricShowContrib = function() private$..symmetricShowContrib$value,
        symmetricShowQuality = function() private$..symmetricShowQuality$value,
        symmetricShowPoints = function() private$..symmetricShowPoints$value,
        showGeometricPlot = function() private$..showGeometricPlot$value,
        geometricRefVariable = function() private$..geometricRefVariable$value,
        geometricRefCategoryRow = function() private$..geometricRefCategoryRow$value,
        geometricRefCategoryCol = function() private$..geometricRefCategoryCol$value,
        showContribPlot = function() private$..showContribPlot$value,
        contribFocus = function() private$..contribFocus$value,
        contribShowClusters = function() private$..contribShowClusters$value,
        showQuality = function() private$..showQuality$value,
        hideWeakContrib = function() private$..hideWeakContrib$value,
        showScreePlot = function() private$..showScreePlot$value,
        equalScale = function() private$..equalScale$value,
        dotSize = function() private$..dotSize$value,
        labelSize = function() private$..labelSize$value,
        clusterAlpha = function() private$..clusterAlpha$value,
        showOverdispersionPlot = function() private$..showOverdispersionPlot$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..showSummary = NA,
        ..showSeriatedTable = NA,
        ..showInertia = NA,
        ..showDimDef = NA,
        ..showDimSummary = NA,
        ..showProfiles = NA,
        ..showCellContrib = NA,
        ..showCorrelations = NA,
        ..showInterpretation = NA,
        ..showSRDTable = NA,
        ..showSymmetricCoords = NA,
        ..showContribCoords = NA,
        ..showQualityContrib = NA,
        ..qualityThreshold = NA,
        ..residualThreshold = NA,
        ..distanceMetric = NA,
        ..residualType = NA,
        ..nAxes = NA,
        ..dim1 = NA,
        ..dim2 = NA,
        ..showSymmetricPlot = NA,
        ..symmetricShowClusters = NA,
        ..symmetricClusterTarget = NA,
        ..symmetricShowContrib = NA,
        ..symmetricShowQuality = NA,
        ..symmetricShowPoints = NA,
        ..showGeometricPlot = NA,
        ..geometricRefVariable = NA,
        ..geometricRefCategoryRow = NA,
        ..geometricRefCategoryCol = NA,
        ..showContribPlot = NA,
        ..contribFocus = NA,
        ..contribShowClusters = NA,
        ..showQuality = NA,
        ..hideWeakContrib = NA,
        ..showScreePlot = NA,
        ..equalScale = NA,
        ..dotSize = NA,
        ..labelSize = NA,
        ..clusterAlpha = NA,
        ..showOverdispersionPlot = NA,
        ..showMethodInfo = NA)
)

caResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "caResults",
    inherit = jmvcore::Group,
    active = list(
        observedTable = function() private$.items[["observedTable"]],
        summaryTable = function() private$.items[["summaryTable"]],
        inertiaTable = function() private$.items[["inertiaTable"]],
        symmetricCoordsTable = function() private$.items[["symmetricCoordsTable"]],
        contribCoordsTable = function() private$.items[["contribCoordsTable"]],
        qualityContribTable = function() private$.items[["qualityContribTable"]],
        dimDefTable = function() private$.items[["dimDefTable"]],
        dimSummaryTable = function() private$.items[["dimSummaryTable"]],
        correlTable = function() private$.items[["correlTable"]],
        interpTable = function() private$.items[["interpTable"]],
        profilesTable = function() private$.items[["profilesTable"]],
        residualMatrixTable = function() private$.items[["residualMatrixTable"]],
        srdTable = function() private$.items[["srdTable"]],
        seriatedTable = function() private$.items[["seriatedTable"]],
        screePlot = function() private$.items[["screePlot"]],
        symmetricPlot = function() private$.items[["symmetricPlot"]],
        geometricPlot = function() private$.items[["geometricPlot"]],
        contribPlot = function() private$.items[["contribPlot"]],
        overdispersionPlot = function() private$.items[["overdispersionPlot"]],
        methodInfo = function() private$.items[["methodInfo"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correspondence Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="observedTable",
                title="Observed Contingency Table",
                visible=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Summary",
                rows=1,
                refs=list(
                    "beh2012",
                    "beh2014",
                    "greenacre2017"),
                visible="(showSummary)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="totalInertia", 
                        `title`="Total Inertia", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="nRows", 
                        `title`="Rows", 
                        `type`="integer"),
                    list(
                        `name`="nCols", 
                        `title`="Columns", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="inertiaTable",
                title="Inertia Decomposition",
                refs=list(
                    "beh2014",
                    "greenacre2017",
                    "saporta2006"),
                visible="(showInertia)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="dim", 
                        `title`="Dimension", 
                        `type`="integer"),
                    list(
                        `name`="eigenvalue", 
                        `title`="Eigenvalue", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="percent", 
                        `title`="%", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cumPercent", 
                        `title`="Cumulative %", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="malinChi", 
                        `title`="Statistic", 
                        `superTitle`="Malinvaud's Test", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="malinDf", 
                        `title`="df", 
                        `superTitle`="Malinvaud's Test", 
                        `type`="integer"),
                    list(
                        `name`="malinP", 
                        `title`="p", 
                        `superTitle`="Malinvaud's Test", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="symmetricCoordsTable",
                title="Principal Coordinates (Symmetric Plot)",
                refs="greenacre2017",
                visible="(showSymmetricCoords)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="contribCoordsTable",
                title="Coordinates (Contribution Biplot)",
                refs="greenacre2017",
                visible="(showContribCoords)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "contribFocus",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="coordType", 
                        `title`="Coordinate Type", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="qualityContribTable",
                title="Quality & Contributions",
                refs="greenacre2017",
                visible="(showQualityContrib)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dimDefTable",
                title="Dimension Definition",
                refs="greenacre2017",
                visible="(showDimDef)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "contribFocus",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="dimension", 
                        `title`="Dimension", 
                        `type`="text"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="contrib", 
                        `title`="Contribution %", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="cumulContrib", 
                        `title`="Cumulative %", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="direction", 
                        `title`="Direction", 
                        `type`="text"),
                    list(
                        `name`="avgContrib", 
                        `title`="Avg %", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`=FALSE))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dimSummaryTable",
                title="Dimension Summary",
                refs="greenacre2017",
                visible="(showDimSummary)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "contribFocus",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="dimension", 
                        `title`="Dimension", 
                        `type`="text"),
                    list(
                        `name`="variance", 
                        `title`="% Inertia", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="negativePole", 
                        `title`="Negative Pole (\u2212)", 
                        `type`="text"),
                    list(
                        `name`="positivePole", 
                        `title`="Positive Pole (+)", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="correlTable",
                title="Correlations with Dimensions",
                refs="greenacre2017",
                visible="(showCorrelations)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "contribFocus",
                    "distanceMetric",
                    "residualType",
                    "qualityThreshold"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="interpTable",
                title="Interpretation Summary",
                refs="greenacre2017",
                visible="(showInterpretation)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "contribFocus",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Defining Category", 
                        `type`="text"),
                    list(
                        `name`="direction", 
                        `title`="Direction", 
                        `type`="text"),
                    list(
                        `name`="association", 
                        `title`="Associated Categories", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="profilesTable",
                title="Profiles",
                refs="greenacre2017",
                visible="(showProfiles)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "contribFocus",
                    "distanceMetric",
                    "residualType"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="residualMatrixTable",
                title="Residual Matrix",
                refs=list(
                    "beh2018"),
                visible="(showCellContrib)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "distanceMetric",
                    "residualType",
                    "residualThreshold"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="srdTable",
                title="SRD Clusters",
                refs="ortontyers1991",
                visible="(showSRDTable)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "contribFocus",
                    "clusterAlpha",
                    "distanceMetric",
                    "residualType"),
                columns=list(
                    list(
                        `name`="cluster", 
                        `title`="Cluster", 
                        `type`="integer"),
                    list(
                        `name`="members", 
                        `title`="Categories", 
                        `type`="text"),
                    list(
                        `name`="nMembers", 
                        `title`="n", 
                        `type`="integer"),
                    list(
                        `name`="mergePvalue", 
                        `title`="Merge p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="seriatedTable",
                title="Seriated Contingency Table",
                visible="(showSeriatedTable)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "dim1",
                    "dim2",
                    "distanceMetric",
                    "residualType"),
                columns=list()))
            self$add(jmvcore::Image$new(
                options=options,
                name="screePlot",
                title="Scree Plot",
                width=500,
                height=400,
                renderFun=".plotScree",
                visible="(showScreePlot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "distanceMetric",
                    "residualType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="symmetricPlot",
                title="Symmetric CA Plot",
                width=650,
                height=550,
                renderFun=".plotSymmetric",
                refs=list(
                    "beh2014",
                    "greenacre2017"),
                visible="(showSymmetricPlot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "dim1",
                    "dim2",
                    "equalScale",
                    "dotSize",
                    "labelSize",
                    "symmetricShowClusters",
                    "symmetricClusterTarget",
                    "symmetricShowContrib",
                    "symmetricShowQuality",
                    "symmetricShowPoints",
                    "clusterAlpha",
                    "distanceMetric",
                    "residualType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="geometricPlot",
                title="Geometric Interpretation Plot",
                width=650,
                height=550,
                renderFun=".plotGeometric",
                refs=list(
                    "borggroenen2005",
                    "yelland2010"),
                visible="(showGeometricPlot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "dim1",
                    "dim2",
                    "equalScale",
                    "dotSize",
                    "labelSize",
                    "geometricRefVariable",
                    "geometricRefCategoryRow",
                    "geometricRefCategoryCol",
                    "distanceMetric",
                    "residualType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="contribPlot",
                title="Contribution Biplot",
                width=650,
                height=550,
                renderFun=".plotContribBiplot",
                refs="greenacre2017",
                visible="(showContribPlot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "nAxes",
                    "dim1",
                    "dim2",
                    "contribFocus",
                    "equalScale",
                    "dotSize",
                    "labelSize",
                    "showQuality",
                    "hideWeakContrib",
                    "contribShowClusters",
                    "clusterAlpha",
                    "distanceMetric",
                    "residualType")))
            self$add(jmvcore::Image$new(
                options=options,
                name="overdispersionPlot",
                title="Overdispersion Diagnostic Plot",
                width=550,
                height=450,
                renderFun=".plotOverdispersion",
                refs="beh2018",
                visible="(showOverdispersionPlot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts")))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "rows",
                    "cols",
                    "distanceMetric",
                    "residualType",
                    "contribFocus",
                    "contribShowClusters",
                    "symmetricShowClusters")))}))

caBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "caBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "ca",
                version = c(1,2,1),
                options = options,
                results = caResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Correspondence Analysis
#'
#' Performs Correspondence Analysis (CA) with multiple visualisation options: 
#' Symmetric CA Plot, Geometric Interpretation Plot, and Contribution Biplot. 
#' Supports both Pearson residuals (chi-squared distance) and Freeman-Tukey 
#' residuals (Hellinger distance), with optional adjusted standardised 
#' residuals for the Pearson framework. The contribution biplot shows which 
#' categories  define each dimension, while interpretive tables identify 
#' association  patterns using distance-based clustering.
#' 
#'
#' @examples
#' \donttest{
#' data('HairEyeColor')
#' dat <- as.data.frame(HairEyeColor)
#'
#' corrAnalysis::ca(
#'     data = dat,
#'     rows = 'Hair',
#'     cols = 'Eye',
#'     counts = 'Freq'
#' )
#'}
#' @param data The dataset containing the variables for analysis.
#' @param rows The categorical variable defining the rows of the contingency
#'   table.
#' @param cols The categorical variable defining the columns of the
#'   contingency table.
#' @param counts For pre-aggregated (frequency-form) data, specify the
#'   variable  containing frequency counts. Leave empty for case-form data.
#' @param showSummary Display summary table with test statistic, df, p-value,
#'   and total inertia.
#' @param showSeriatedTable Display the contingency table with rows and
#'   columns reordered by their principal coordinates (CA seriation). Marginals
#'   show the coordinate  values used for ordering. This reveals gradient
#'   structures in the data.
#' @param showInertia Display inertia table with Malinvaud's test.
#' @param showDimDef Display table showing which categories define each
#'   dimension.
#' @param showDimSummary Display compact table showing which categories define
#'   each pole of each dimension. Only above-average contributors are shown.
#' @param showProfiles Display table showing the profiles of interpreted
#'   categories (the variable opposite to the plane-defining variable).
#' @param showCellContrib Display residuals in matrix form with marginal
#'   percentages showing each row's and column's contribution to the total
#'   statistic. Residuals exceeding the threshold are highlighted, as are
#'   marginal percentages above the average contribution.
#' @param showCorrelations Display table showing category correlations
#'   (±√cos²) with each dimension.
#' @param showInterpretation Display table summarising associations between
#'   interpreted categories and the dimension-defining categories.
#' @param showSRDTable Display table showing clusters from distance-based
#'   analysis.
#' @param showSymmetricCoords Display table of principal coordinates for both
#'   row and column categories, as used in the symmetric CA plot.
#' @param showContribCoords Display table of coordinates as used in the
#'   contribution biplot. The plane-defining variable is shown in standard
#'   coordinates; the interpreted variable is shown in principal coordinates.
#' @param showQualityContrib Display table showing quality of representation
#'   (cos²) and contributions for all categories across all extracted
#'   dimensions. Categories are sorted by total quality (descending). Useful for
#'   assessing which categories are well-represented and influential.
#' @param qualityThreshold Hide categories with quality below this threshold
#'   from the  correlations table. Set to 0 to show all categories.
#' @param residualThreshold Residuals with absolute value exceeding this
#'   threshold are highlighted. Default is 1.96 (approximately p < 0.05
#'   two-tailed). Set to 0 to disable highlighting.
#' @param distanceMetric Distance metric for CA decomposition. Pearson
#'   residuals yield chi-squared distances (classical approach). Freeman-Tukey
#'   residuals yield Hellinger distances and are more robust to overdispersion
#'   in sparse tables (Beh, Lombardo & Alberti, 2018).
#' @param residualType Type of residuals when using Pearson metric.
#'   Standardised residuals are classical (O-E)/√E. Adjusted standardised
#'   residuals account for marginal constraints, providing more accurate
#'   significance testing. This option is ignored when Freeman-Tukey metric is
#'   selected.
#' @param nAxes Number of CA dimensions to extract. Default is 2.
#' @param dim1 Which dimension to display on the horizontal axis.
#' @param dim2 Which dimension to display on the vertical axis.
#' @param showSymmetricPlot Display the classic symmetric CA scatterplot with
#'   row and column categories in principal coordinates.
#' @param symmetricShowClusters Display convex hulls around clusters of
#'   interpreted categories on the symmetric plot.
#' @param symmetricClusterTarget Which categories to cluster on the symmetric
#'   plot. 'Both' will show separate cluster hulls for row and column
#'   categories.
#' @param symmetricShowContrib Scale point sizes by contribution to the
#'   displayed plane (sum of contributions to the two displayed dimensions).
#'   Larger points indicate categories that contribute more to defining the
#'   plane.
#' @param symmetricShowQuality Adjust point transparency by quality of
#'   representation (cos²) on the displayed plane. Fully opaque points are
#'   well-represented; faded points have low quality and should be interpreted
#'   cautiously.
#' @param symmetricShowPoints Which categories to display on the symmetric
#'   plot. 'Rows only' hides column points and labels; 'Columns only' hides row
#'   points and labels. Useful for reducing clutter in crowded plots.
#' @param showGeometricPlot Display geometric interpretation plot
#'   (Borg-Groenen 2005; Yelland 2010). This visualisation helps interpret
#'   relative frequencies by projecting categories onto the line through the
#'   origin and a reference category.
#' @param geometricRefVariable Which variable contains the reference category
#'   for geometric interpretation.
#' @param geometricRefCategoryRow The row category to use as reference when
#'   Reference variable = Row categories. Categories projecting on the same side
#'   of the origin as this reference  have above-average association; those on
#'   the opposite side have below-average.
#' @param geometricRefCategoryCol The column category to use as reference when
#'   Reference variable = Column categories. Categories projecting on the same
#'   side of the origin as this reference  have above-average association; those
#'   on the opposite side have below-average.
#' @param showContribPlot Display the contribution biplot.
#' @param contribFocus Which variable's categories define the CA plane (shown
#'   with lines  to origin). The other variable's categories are interpreted
#'   relative to these dimensions.
#' @param contribShowClusters Display convex hulls around clusters of
#'   interpreted categories on the contribution biplot.
#' @param showQuality Colour interpreted categories by their quality of
#'   representation.
#' @param hideWeakContrib Hide labels for plane-defining categories
#'   contributing below average.
#' @param showScreePlot Display a scree plot showing inertia by dimension.
#' @param equalScale Use equal scaling on both axes.
#' @param dotSize Size of points in the plots.
#' @param labelSize Size of category labels.
#' @param clusterAlpha Significance level for distance-based clustering.
#'   Categories with statistically indistinguishable profiles (p > alpha) are
#'   grouped.
#' @param showOverdispersionPlot Display a diagnostic plot for overdispersion
#'   (Beh, Lombardo & Alberti,  2018). If points cluster to the left side of the
#'   plot rather than  scattering randomly, overdispersion is present and
#'   Freeman-Tukey  residuals should be used instead of Pearson residuals.
#' @param showMethodInfo Display detailed methodological explanations for
#'   correspondence analysis, including descriptions of residual types, distance
#'   metrics, contribution biplots, and clustering procedures.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$observedTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$inertiaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$symmetricCoordsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contribCoordsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$qualityContribTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dimDefTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dimSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$correlTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$interpTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$profilesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residualMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$srdTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$seriatedTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$screePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$symmetricPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$geometricPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$contribPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$overdispersionPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$observedTable$asDF}
#'
#' \code{as.data.frame(results$observedTable)}
#'
#' @export
ca <- function(
    data,
    rows,
    cols,
    counts = NULL,
    showSummary = TRUE,
    showSeriatedTable = FALSE,
    showInertia = TRUE,
    showDimDef = FALSE,
    showDimSummary = FALSE,
    showProfiles = FALSE,
    showCellContrib = FALSE,
    showCorrelations = FALSE,
    showInterpretation = FALSE,
    showSRDTable = FALSE,
    showSymmetricCoords = TRUE,
    showContribCoords = FALSE,
    showQualityContrib = TRUE,
    qualityThreshold = 0,
    residualThreshold = 1.96,
    distanceMetric = "pearson",
    residualType = "standardised",
    nAxes = 2,
    dim1 = 1,
    dim2 = 2,
    showSymmetricPlot = TRUE,
    symmetricShowClusters = FALSE,
    symmetricClusterTarget = "rows",
    symmetricShowContrib = "none",
    symmetricShowQuality = "none",
    symmetricShowPoints = "both",
    showGeometricPlot = FALSE,
    geometricRefVariable = "rows",
    geometricRefCategoryRow,
    geometricRefCategoryCol,
    showContribPlot = FALSE,
    contribFocus = "cols",
    contribShowClusters = FALSE,
    showQuality = FALSE,
    hideWeakContrib = FALSE,
    showScreePlot = FALSE,
    equalScale = TRUE,
    dotSize = 2.5,
    labelSize = 3.5,
    clusterAlpha = 0.05,
    showOverdispersionPlot = FALSE,
    showMethodInfo = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ca requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- caOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        showSummary = showSummary,
        showSeriatedTable = showSeriatedTable,
        showInertia = showInertia,
        showDimDef = showDimDef,
        showDimSummary = showDimSummary,
        showProfiles = showProfiles,
        showCellContrib = showCellContrib,
        showCorrelations = showCorrelations,
        showInterpretation = showInterpretation,
        showSRDTable = showSRDTable,
        showSymmetricCoords = showSymmetricCoords,
        showContribCoords = showContribCoords,
        showQualityContrib = showQualityContrib,
        qualityThreshold = qualityThreshold,
        residualThreshold = residualThreshold,
        distanceMetric = distanceMetric,
        residualType = residualType,
        nAxes = nAxes,
        dim1 = dim1,
        dim2 = dim2,
        showSymmetricPlot = showSymmetricPlot,
        symmetricShowClusters = symmetricShowClusters,
        symmetricClusterTarget = symmetricClusterTarget,
        symmetricShowContrib = symmetricShowContrib,
        symmetricShowQuality = symmetricShowQuality,
        symmetricShowPoints = symmetricShowPoints,
        showGeometricPlot = showGeometricPlot,
        geometricRefVariable = geometricRefVariable,
        geometricRefCategoryRow = geometricRefCategoryRow,
        geometricRefCategoryCol = geometricRefCategoryCol,
        showContribPlot = showContribPlot,
        contribFocus = contribFocus,
        contribShowClusters = contribShowClusters,
        showQuality = showQuality,
        hideWeakContrib = hideWeakContrib,
        showScreePlot = showScreePlot,
        equalScale = equalScale,
        dotSize = dotSize,
        labelSize = labelSize,
        clusterAlpha = clusterAlpha,
        showOverdispersionPlot = showOverdispersionPlot,
        showMethodInfo = showMethodInfo)

    analysis <- caClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

