
# This file is automatically generated, you probably don't want to edit this

chisqpowerOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqpowerOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            analysisType = "apriori",
            nRows = 2,
            nCols = 2,
            esType = "w",
            effectSize = 0.3,
            esConventional = "medium",
            alpha = 0.05,
            power = 0.8,
            n = 100,
            showRefTable = TRUE,
            showPowerCurve = TRUE,
            showESCurve = FALSE,
            showMethodInfo = FALSE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqpower",
                requiresData=TRUE,
                ...)

            private$..analysisType <- jmvcore::OptionList$new(
                "analysisType",
                analysisType,
                options=list(
                    "apriori",
                    "posthoc",
                    "sensitivity"),
                default="apriori")
            private$..nRows <- jmvcore::OptionInteger$new(
                "nRows",
                nRows,
                min=2,
                max=20,
                default=2)
            private$..nCols <- jmvcore::OptionInteger$new(
                "nCols",
                nCols,
                min=2,
                max=20,
                default=2)
            private$..esType <- jmvcore::OptionList$new(
                "esType",
                esType,
                options=list(
                    "w",
                    "v",
                    "conventional"),
                default="w")
            private$..effectSize <- jmvcore::OptionNumber$new(
                "effectSize",
                effectSize,
                min=0.001,
                max=2,
                default=0.3)
            private$..esConventional <- jmvcore::OptionList$new(
                "esConventional",
                esConventional,
                options=list(
                    "small",
                    "medium",
                    "large"),
                default="medium")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0.001,
                max=0.5,
                default=0.05)
            private$..power <- jmvcore::OptionNumber$new(
                "power",
                power,
                min=0.1,
                max=0.999,
                default=0.8)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n,
                min=4,
                max=1000000,
                default=100)
            private$..showRefTable <- jmvcore::OptionBool$new(
                "showRefTable",
                showRefTable,
                default=TRUE)
            private$..showPowerCurve <- jmvcore::OptionBool$new(
                "showPowerCurve",
                showPowerCurve,
                default=TRUE)
            private$..showESCurve <- jmvcore::OptionBool$new(
                "showESCurve",
                showESCurve,
                default=FALSE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)

            self$.addOption(private$..analysisType)
            self$.addOption(private$..nRows)
            self$.addOption(private$..nCols)
            self$.addOption(private$..esType)
            self$.addOption(private$..effectSize)
            self$.addOption(private$..esConventional)
            self$.addOption(private$..alpha)
            self$.addOption(private$..power)
            self$.addOption(private$..n)
            self$.addOption(private$..showRefTable)
            self$.addOption(private$..showPowerCurve)
            self$.addOption(private$..showESCurve)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        analysisType = function() private$..analysisType$value,
        nRows = function() private$..nRows$value,
        nCols = function() private$..nCols$value,
        esType = function() private$..esType$value,
        effectSize = function() private$..effectSize$value,
        esConventional = function() private$..esConventional$value,
        alpha = function() private$..alpha$value,
        power = function() private$..power$value,
        n = function() private$..n$value,
        showRefTable = function() private$..showRefTable$value,
        showPowerCurve = function() private$..showPowerCurve$value,
        showESCurve = function() private$..showESCurve$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..analysisType = NA,
        ..nRows = NA,
        ..nCols = NA,
        ..esType = NA,
        ..effectSize = NA,
        ..esConventional = NA,
        ..alpha = NA,
        ..power = NA,
        ..n = NA,
        ..showRefTable = NA,
        ..showPowerCurve = NA,
        ..showESCurve = NA,
        ..showMethodInfo = NA)
)

chisqpowerResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqpowerResults",
    inherit = jmvcore::Group,
    active = list(
        resultsTable = function() private$.items[["resultsTable"]],
        refTable = function() private$.items[["refTable"]],
        powerCurvePlot = function() private$.items[["powerCurvePlot"]],
        esCurvePlot = function() private$.items[["esCurvePlot"]],
        methodInfo = function() private$.items[["methodInfo"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Power Analysis for Chi-Squared Test",
                refs=list(
                    "cohen1988",
                    "cohen1992"))
            self$add(jmvcore::Table$new(
                options=options,
                name="resultsTable",
                title="Power Analysis Results",
                refs=list(
                    "cohen1988"),
                clearWith=list(
                    "analysisType",
                    "nRows",
                    "nCols",
                    "esType",
                    "effectSize",
                    "esConventional",
                    "alpha",
                    "power",
                    "n"),
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="refTable",
                title="Sample Size Reference Table",
                visible="(showRefTable)",
                refs=list(
                    "cohen1992"),
                clearWith=list(
                    "nRows",
                    "nCols",
                    "alpha"),
                columns=list(
                    list(
                        `name`="power", 
                        `title`="Power", 
                        `type`="text"),
                    list(
                        `name`="small", 
                        `title`="w = 0.1", 
                        `type`="integer", 
                        `superTitle`="Required N"),
                    list(
                        `name`="medium", 
                        `title`="w = 0.3", 
                        `type`="integer", 
                        `superTitle`="Required N"),
                    list(
                        `name`="large", 
                        `title`="w = 0.5", 
                        `type`="integer", 
                        `superTitle`="Required N"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerCurvePlot",
                title="Power Curve",
                width=550,
                height=400,
                renderFun=".plotPowerCurve",
                visible="(showPowerCurve)",
                requiresData=FALSE,
                clearWith=list(
                    "analysisType",
                    "nRows",
                    "nCols",
                    "esType",
                    "effectSize",
                    "esConventional",
                    "alpha",
                    "power",
                    "n")))
            self$add(jmvcore::Image$new(
                options=options,
                name="esCurvePlot",
                title="Effect Size Sensitivity Curve",
                width=550,
                height=400,
                renderFun=".plotESCurve",
                visible="(showESCurve)",
                requiresData=FALSE,
                clearWith=list(
                    "analysisType",
                    "nRows",
                    "nCols",
                    "alpha",
                    "power",
                    "n")))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "analysisType",
                    "esType")))}))

chisqpowerBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqpowerBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqpower",
                version = c(1,0,0),
                options = options,
                results = chisqpowerResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Power Analysis for Chi-Squared Test
#'
#' Power analysis for chi-squared tests of independence.
#' 
#' Provides three types of analysis:
#' - A priori: Calculate required sample size given effect size, alpha, and 
#' power
#' - Post-hoc: Calculate achieved power given effect size, alpha, and sample 
#' size
#' - Sensitivity: Calculate detectable effect size given alpha, power, and 
#' sample size
#' 
#' Effect sizes can be specified as Cohen's w or Cramér's V. Conventional 
#' effect size thresholds (small = 0.1, medium = 0.3, large = 0.5) are 
#' available.
#' 
#' Results include detailed parameter tables, sample size reference tables for
#' planning, and power curve visualisations.
#' 
#'
#' @examples
#' # A priori power analysis: How many participants needed?
#' chisqpower(
#'     analysisType = 'apriori',
#'     nRows = 3,
#'     nCols = 4,
#'     effectSize = 0.3,
#'     alpha = 0.05,
#'     power = 0.80
#' )
#'
#' # Post-hoc power analysis: What power did my study have?
#' chisqpower(
#'     analysisType = 'posthoc',
#'     nRows = 2,
#'     nCols = 2,
#'     effectSize = 0.25,
#'     alpha = 0.05,
#'     n = 100
#' )
#'
#' # Sensitivity analysis: What effect could I detect?
#' chisqpower(
#'     analysisType = 'sensitivity',
#'     nRows = 3,
#'     nCols = 3,
#'     alpha = 0.05,
#'     power = 0.80,
#'     n = 200
#' )
#'
#' @param data not used for power analysis; included for compatibility
#' @param analysisType type of power analysis: 'apriori' (default) computes
#'   required sample size, 'posthoc' computes achieved power, 'sensitivity'
#'   computes minimum  detectable effect size
#' @param nRows number of rows in the contingency table (minimum 2, default 2)
#' @param nCols number of columns in the contingency table (minimum 2, default
#'   2)
#' @param esType type of effect size: 'w' for Cohen's w (default), 'v' for
#'   Cramér's V, or 'conventional' for preset thresholds
#' @param effectSize effect size value (Cohen's w or Cramér's V depending on
#'   esType). Default is 0.3 (medium effect for Cohen's w).
#' @param esConventional conventional effect size threshold: 'small' (w =
#'   0.1),  'medium' (w = 0.3, default), or 'large' (w = 0.5)
#' @param alpha significance level (Type I error rate). Default is 0.05.
#' @param power target statistical power (1 minus Type II error rate).
#'   Default is 0.80. Used for a priori and sensitivity analyses.
#' @param n total sample size. Used for post-hoc and sensitivity analyses.
#'   Default is 100.
#' @param showRefTable TRUE (default) or FALSE, display a reference table
#'   showing required sample sizes across effect sizes and power levels
#' @param showPowerCurve TRUE (default) or FALSE, display the power curve
#'   visualisation
#' @param showESCurve TRUE or FALSE (default), display effect size sensitivity
#'   curve showing detectable effect across sample sizes
#' @param showMethodInfo TRUE or FALSE (default), display detailed
#'   methodological explanations for power analysis
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$resultsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$refTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerCurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$esCurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$resultsTable$asDF}
#'
#' \code{as.data.frame(results$resultsTable)}
#'
#' @export
chisqpower <- function(
    data,
    analysisType = "apriori",
    nRows = 2,
    nCols = 2,
    esType = "w",
    effectSize = 0.3,
    esConventional = "medium",
    alpha = 0.05,
    power = 0.8,
    n = 100,
    showRefTable = TRUE,
    showPowerCurve = TRUE,
    showESCurve = FALSE,
    showMethodInfo = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqpower requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- chisqpowerOptions$new(
        analysisType = analysisType,
        nRows = nRows,
        nCols = nCols,
        esType = esType,
        effectSize = effectSize,
        esConventional = esConventional,
        alpha = alpha,
        power = power,
        n = n,
        showRefTable = showRefTable,
        showPowerCurve = showPowerCurve,
        showESCurve = showESCurve,
        showMethodInfo = showMethodInfo)

    analysis <- chisqpowerClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

