
# This file is automatically generated, you probably don't want to edit this

chisqposthocOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqposthocOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            stdres = FALSE,
            momcorrstdres = FALSE,
            adjstdres = TRUE,
            quetelet = FALSE,
            ij = FALSE,
            bsOutlier = FALSE,
            bsKmax = 2,
            pem = FALSE,
            medpolish = FALSE,
            adjmedpolish = FALSE,
            gkres = FALSE,
            dep = FALSE,
            depOutcome = NULL,
            sidakCorrection = FALSE,
            confLevel = 95,
            bootstrapReps = 999,
            seed = 123,
            showPemPlot = FALSE,
            pemPlotFilter = "all",
            showDepPlot = FALSE,
            showMethodInfo = FALSE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqposthoc",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"))
            private$..stdres <- jmvcore::OptionBool$new(
                "stdres",
                stdres,
                default=FALSE)
            private$..momcorrstdres <- jmvcore::OptionBool$new(
                "momcorrstdres",
                momcorrstdres,
                default=FALSE)
            private$..adjstdres <- jmvcore::OptionBool$new(
                "adjstdres",
                adjstdres,
                default=TRUE)
            private$..quetelet <- jmvcore::OptionBool$new(
                "quetelet",
                quetelet,
                default=FALSE)
            private$..ij <- jmvcore::OptionBool$new(
                "ij",
                ij,
                default=FALSE)
            private$..bsOutlier <- jmvcore::OptionBool$new(
                "bsOutlier",
                bsOutlier,
                default=FALSE)
            private$..bsKmax <- jmvcore::OptionInteger$new(
                "bsKmax",
                bsKmax,
                min=1,
                max=100,
                default=2)
            private$..pem <- jmvcore::OptionBool$new(
                "pem",
                pem,
                default=FALSE)
            private$..medpolish <- jmvcore::OptionBool$new(
                "medpolish",
                medpolish,
                default=FALSE)
            private$..adjmedpolish <- jmvcore::OptionBool$new(
                "adjmedpolish",
                adjmedpolish,
                default=FALSE)
            private$..gkres <- jmvcore::OptionBool$new(
                "gkres",
                gkres,
                default=FALSE)
            private$..dep <- jmvcore::OptionBool$new(
                "dep",
                dep,
                default=FALSE)
            private$..depOutcome <- jmvcore::OptionLevel$new(
                "depOutcome",
                depOutcome,
                variable="(cols)")
            private$..sidakCorrection <- jmvcore::OptionBool$new(
                "sidakCorrection",
                sidakCorrection,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                min=50,
                max=99.9,
                default=95)
            private$..bootstrapReps <- jmvcore::OptionInteger$new(
                "bootstrapReps",
                bootstrapReps,
                min=100,
                max=10000,
                default=999)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                min=1,
                max=999999,
                default=123)
            private$..showPemPlot <- jmvcore::OptionBool$new(
                "showPemPlot",
                showPemPlot,
                default=FALSE)
            private$..pemPlotFilter <- jmvcore::OptionList$new(
                "pemPlotFilter",
                pemPlotFilter,
                options=list(
                    "all",
                    "sigOnly",
                    "nonsigOnly"),
                default="all")
            private$..showDepPlot <- jmvcore::OptionBool$new(
                "showDepPlot",
                showDepPlot,
                default=FALSE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..stdres)
            self$.addOption(private$..momcorrstdres)
            self$.addOption(private$..adjstdres)
            self$.addOption(private$..quetelet)
            self$.addOption(private$..ij)
            self$.addOption(private$..bsOutlier)
            self$.addOption(private$..bsKmax)
            self$.addOption(private$..pem)
            self$.addOption(private$..medpolish)
            self$.addOption(private$..adjmedpolish)
            self$.addOption(private$..gkres)
            self$.addOption(private$..dep)
            self$.addOption(private$..depOutcome)
            self$.addOption(private$..sidakCorrection)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..bootstrapReps)
            self$.addOption(private$..seed)
            self$.addOption(private$..showPemPlot)
            self$.addOption(private$..pemPlotFilter)
            self$.addOption(private$..showDepPlot)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        stdres = function() private$..stdres$value,
        momcorrstdres = function() private$..momcorrstdres$value,
        adjstdres = function() private$..adjstdres$value,
        quetelet = function() private$..quetelet$value,
        ij = function() private$..ij$value,
        bsOutlier = function() private$..bsOutlier$value,
        bsKmax = function() private$..bsKmax$value,
        pem = function() private$..pem$value,
        medpolish = function() private$..medpolish$value,
        adjmedpolish = function() private$..adjmedpolish$value,
        gkres = function() private$..gkres$value,
        dep = function() private$..dep$value,
        depOutcome = function() private$..depOutcome$value,
        sidakCorrection = function() private$..sidakCorrection$value,
        confLevel = function() private$..confLevel$value,
        bootstrapReps = function() private$..bootstrapReps$value,
        seed = function() private$..seed$value,
        showPemPlot = function() private$..showPemPlot$value,
        pemPlotFilter = function() private$..pemPlotFilter$value,
        showDepPlot = function() private$..showDepPlot$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..stdres = NA,
        ..momcorrstdres = NA,
        ..adjstdres = NA,
        ..quetelet = NA,
        ..ij = NA,
        ..bsOutlier = NA,
        ..bsKmax = NA,
        ..pem = NA,
        ..medpolish = NA,
        ..adjmedpolish = NA,
        ..gkres = NA,
        ..dep = NA,
        ..depOutcome = NA,
        ..sidakCorrection = NA,
        ..confLevel = NA,
        ..bootstrapReps = NA,
        ..seed = NA,
        ..showPemPlot = NA,
        ..pemPlotFilter = NA,
        ..showDepPlot = NA,
        ..showMethodInfo = NA)
)

chisqposthocResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqposthocResults",
    inherit = jmvcore::Group,
    active = list(
        crosstabTable = function() private$.items[["crosstabTable"]],
        stdresTable = function() private$.items[["stdresTable"]],
        momcorrstdresTable = function() private$.items[["momcorrstdresTable"]],
        adjstdresTable = function() private$.items[["adjstdresTable"]],
        queteletTable = function() private$.items[["queteletTable"]],
        ijTable = function() private$.items[["ijTable"]],
        bsOutlierMatrixTable = function() private$.items[["bsOutlierMatrixTable"]],
        bsOutlierDetailTable = function() private$.items[["bsOutlierDetailTable"]],
        pemTable = function() private$.items[["pemTable"]],
        pemPlot = function() private$.items[["pemPlot"]],
        medpolishTable = function() private$.items[["medpolishTable"]],
        adjmedpolishTable = function() private$.items[["adjmedpolishTable"]],
        gkresColTable = function() private$.items[["gkresColTable"]],
        gkresRowTable = function() private$.items[["gkresRowTable"]],
        depTable = function() private$.items[["depTable"]],
        depPlot = function() private$.items[["depPlot"]],
        methodInfo = function() private$.items[["methodInfo"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Chi-Squared Post-Hoc Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="crosstabTable",
                title="Observed Contingency Table",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "stdres",
                    "momcorrstdres",
                    "adjstdres",
                    "quetelet",
                    "ij",
                    "bsOutlier",
                    "pem",
                    "medpolish",
                    "adjmedpolish",
                    "gkres",
                    "dep",
                    "sidakCorrection"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="stdresTable",
                title="Standardised Residuals",
                visible="(stdres)",
                clearWith=list(
                    "rows",
                    "cols",
                    "sidakCorrection",
                    "stdres"),
                columns=list(),
                refs=list(
                    "agresti2013")))
            self$add(jmvcore::Table$new(
                options=options,
                name="momcorrstdresTable",
                title="Moment-Corrected Standardised Residuals",
                visible="(momcorrstdres)",
                clearWith=list(
                    "rows",
                    "cols",
                    "sidakCorrection",
                    "momcorrstdres"),
                columns=list(),
                refs=list(
                    "garciaperez2003")))
            self$add(jmvcore::Table$new(
                options=options,
                name="adjstdresTable",
                title="Adjusted Standardised Residuals",
                visible="(adjstdres)",
                clearWith=list(
                    "rows",
                    "cols",
                    "sidakCorrection",
                    "adjstdres"),
                columns=list(),
                refs=list(
                    "haberman1973")))
            self$add(jmvcore::Table$new(
                options=options,
                name="queteletTable",
                title="Quetelet Index",
                visible="(quetelet)",
                clearWith=list(
                    "rows",
                    "cols",
                    "quetelet"),
                columns=list(),
                refs=list(
                    "mirkin2001",
                    "mirkin2023")))
            self$add(jmvcore::Table$new(
                options=options,
                name="ijTable",
                title="IJ Association Factor",
                visible="(ij)",
                clearWith=list(
                    "rows",
                    "cols",
                    "ij"),
                columns=list(),
                refs=list(
                    "good1956",
                    "agresti2013")))
            self$add(jmvcore::Table$new(
                options=options,
                name="bsOutlierMatrixTable",
                title="Deleted Residuals (Backwards-Stepping)",
                visible="(bsOutlier)",
                clearWith=list(
                    "rows",
                    "cols",
                    "bsKmax"),
                columns=list(),
                refs=list(
                    "simonoff1988")))
            self$add(jmvcore::Table$new(
                options=options,
                name="bsOutlierDetailTable",
                title="Backwards-Stepping Identified Cells",
                visible="(bsOutlier)",
                clearWith=list(
                    "rows",
                    "cols",
                    "bsKmax"),
                columns=list(
                    list(
                        `name`="rank", 
                        `title`="Rank", 
                        `type`="integer"),
                    list(
                        `name`="cell", 
                        `title`="Cell", 
                        `type`="text"),
                    list(
                        `name`="delRes", 
                        `title`="Deleted Residual", 
                        `type`="number"),
                    list(
                        `name`="g2Drop", 
                        `title`="G\u00B2 Drop", 
                        `type`="number"),
                    list(
                        `name`="detected", 
                        `title`="Detected", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="pemTable",
                title="PEM with Confidence Intervals",
                visible="(pem)",
                clearWith=list(
                    "rows",
                    "cols",
                    "confLevel",
                    "bootstrapReps"),
                columns=list(),
                refs=list(
                    "cibois1993",
                    "lefevrechampely2009",
                    "sakoda1981")))
            self$add(jmvcore::Image$new(
                options=options,
                name="pemPlot",
                title="PEM Forest Plot",
                visible="(pem && showPemPlot)",
                width=700,
                height=500,
                renderFun=".pemPlot",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "confLevel",
                    "bootstrapReps",
                    "seed",
                    "pemPlotFilter")))
            self$add(jmvcore::Table$new(
                options=options,
                name="medpolishTable",
                title="Standardised Median Polish Residuals",
                visible="(medpolish)",
                clearWith=list(
                    "rows",
                    "cols",
                    "medpolish"),
                columns=list(),
                refs=list(
                    "mostellerparunak1985",
                    "simonoff2003")))
            self$add(jmvcore::Table$new(
                options=options,
                name="adjmedpolishTable",
                title="Adjusted Standardised Median Polish Residuals",
                visible="(adjmedpolish)",
                clearWith=list(
                    "rows",
                    "cols",
                    "adjmedpolish"),
                columns=list(),
                refs=list(
                    "mostellerparunak1985")))
            self$add(jmvcore::Table$new(
                options=options,
                name="gkresColTable",
                title="Goodman-Kruskal Residuals (Columns as Predictor)",
                visible="(gkres)",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list(),
                refs=list(
                    "kroonenberglombardo1999")))
            self$add(jmvcore::Table$new(
                options=options,
                name="gkresRowTable",
                title="Goodman-Kruskal Residuals (Rows as Predictor)",
                visible="(gkres)",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list(),
                refs=list(
                    "kroonenberglombardo1999")))
            self$add(jmvcore::Table$new(
                options=options,
                name="depTable",
                title="Dependence Evaluator Proportion (DEP)",
                visible="(dep)",
                clearWith=list(
                    "rows",
                    "cols",
                    "depOutcome"),
                columns=list(
                    list(
                        `name`="rowCat", 
                        `title`="Independent Category", 
                        `type`="text"),
                    list(
                        `name`="depOutcome", 
                        `title`="Dependent Category", 
                        `type`="text"),
                    list(
                        `name`="depValue", 
                        `title`="DEP", 
                        `type`="number"),
                    list(
                        `name`="sigLower", 
                        `title`="Sig. Lower", 
                        `type`="number"),
                    list(
                        `name`="sigUpper", 
                        `title`="Sig. Upper", 
                        `type`="number"),
                    list(
                        `name`="significance", 
                        `title`="Significance", 
                        `type`="text")),
                refs=list(
                    "gambirasio2024")))
            self$add(jmvcore::Image$new(
                options=options,
                name="depPlot",
                title="DEP Forest Plot",
                visible="(dep && showDepPlot)",
                width=700,
                height=500,
                renderFun=".depPlot",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "depOutcome")))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "rows",
                    "cols",
                    "stdres",
                    "momcorrstdres",
                    "adjstdres",
                    "quetelet",
                    "ij",
                    "bsOutlier",
                    "pem",
                    "medpolish",
                    "adjmedpolish",
                    "gkres",
                    "dep",
                    "showMethodInfo")))}))

chisqposthocBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqposthocBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqposthoc",
                version = c(1,0,0),
                options = options,
                results = chisqposthocResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Chi-Squared Post-Hoc Analysis
#'
#' Comprehensive post-hoc analysis for chi-squared tests of independence.
#' 
#' Provides multiple cell-level metrics to identify patterns of association:
#' 
#' Symmetric measures (no assumed directionality):
#' - Standardised residuals (with optional Šidák correction)
#' - Moment-corrected standardised residuals (with optional Šidák correction)
#' - Adjusted standardised residuals (with optional Šidák correction)
#' - Quetelet Index
#' - IJ association factor
#' - Backwards-stepping outlier detection (Simonoff 1988)
#' - PEM (Percentage of Maximum deviation from independence)
#' - Standardised median polish residuals
#' - Adjusted standardised median polish residuals
#' 
#' Directional measures (assume predictor → response structure):
#' - Goodman-Kruskal residuals
#' - Dependence Evaluator Proportion (DEP)
#' 
#' Significant positive values are highlighted in red, negative with blue.
#' Significance tables automatically identify attraction/repulsion patterns.
#' 
#'
#' @examples
#' # Example with Titanic data
#' data('Titanic')
#' titanic_df <- as.data.frame(Titanic)
#' titanic_expanded <- titanic_df[rep(seq_len(nrow(titanic_df)),
#'                                    titanic_df$Freq), 1:4]
#'
#' chisqposthoc(
#'     data = titanic_expanded,
#'     rows = 'Class',
#'     cols = 'Survived',
#'     stdres = TRUE,
#'     pem = TRUE,
#'     sidakCorrection = TRUE
#' )
#'
#' @param data the data as a data frame
#' @param rows a string naming the variable for rows in the contingency table
#'   (must be a factor)
#' @param cols a string naming the variable for columns in the contingency
#'   table (must be a factor)
#' @param counts optional variable containing frequency counts for wide-format
#'   data. If not provided, data are assumed to be in long format (one row per
#'   case). The variable will be treated as numeric frequencies.
#' @param stdres TRUE or FALSE (default: FALSE), compute standardised
#'   residuals
#' @param momcorrstdres TRUE or FALSE (default: FALSE), compute
#'   moment-corrected standardised residuals
#' @param adjstdres TRUE or FALSE (default: FALSE), compute adjusted
#'   standardised residuals
#' @param quetelet TRUE or FALSE (default: FALSE), compute Quetelet Index
#' @param ij TRUE or FALSE (default: FALSE), compute IJ association factor
#' @param bsOutlier TRUE or FALSE (default: FALSE), perform backwards-stepping
#'   outlier detection using deleted residuals and G² drop statistics.
#'   Identifies cells that deviate significantly from independence, with
#'   protection against masking and swamping effects. Method from Simonoff
#'   (1988).
#' @param bsKmax maximum number of potential outlier cells to test in
#'   backwards-stepping procedure (default: 5). Simonoff (1988) suggests 20-30\%
#'   of cells. Higher values increase computation time but do not inflate false
#'   positive rates due to Bonferroni correction.
#' @param pem TRUE or FALSE (default: FALSE), compute PEM (Percentage of
#'   Maximum deviation) with bootstrap confidence intervals. PEM is
#'   mathematically equivalent to Sakoda's cell-level index D_ij, expressed as a
#'   percentage rather than proportion.
#' @param medpolish TRUE or FALSE (default: FALSE), compute standardised
#'   median polish residuals
#' @param adjmedpolish TRUE or FALSE (default: FALSE), compute adjusted
#'   standardised median polish residuals
#' @param gkres TRUE or FALSE (default: FALSE), compute Goodman-Kruskal
#'   residuals. These residuals measure how knowing the predictor category
#'   changes the probability of each response category relative to its marginal
#'   probability. Two tables are produced: one treating columns as predictor
#'   (rows as response), one treating rows as predictor (columns as response).
#' @param dep TRUE or FALSE (default: FALSE), compute DEP (Dependence
#'   Evaluator Proportion). This measure requires designating one column
#'   category as the outcome of interest and computes a normalised probability
#'   difference for each row category.
#' @param depOutcome the column category to treat as the outcome of interest
#'   for DEP analysis. Levels are populated from the column variable.
#' @param sidakCorrection TRUE or FALSE (default: FALSE), apply Šidák
#'   correction to  standardised, moment-corrected standardised, and adjusted
#'   standardised residual significance thresholds
#' @param confLevel confidence level as percentage for PEM bootstrap
#'   confidence intervals (default: 0.95)
#' @param bootstrapReps number of bootstrap replications for PEM confidence
#'   intervals (default: 2000)
#' @param seed random seed for reproducibility (default: 123)
#' @param showPemPlot TRUE or FALSE (default: FALSE), display a diverging bar
#'   chart of PEM values with bootstrap confidence intervals, sorted by
#'   magnitude
#' @param pemPlotFilter filter which cells to display in the PEM forest plot:
#'   'all' (default), 'sigOnly', or 'nonsigOnly'
#' @param showDepPlot TRUE or FALSE (default: FALSE), display a forest plot of
#'   DEP values with significance bounds derived from chi-squared critical
#'   values
#' @param showMethodInfo TRUE or FALSE (default: FALSE), display detailed
#'   methodological  explanations for all selected metrics
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$crosstabTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$stdresTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$momcorrstdresTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$adjstdresTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$queteletTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ijTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bsOutlierMatrixTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bsOutlierDetailTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pemTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pemPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$medpolishTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$adjmedpolishTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$gkresColTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$gkresRowTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$depTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$depPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crosstabTable$asDF}
#'
#' \code{as.data.frame(results$crosstabTable)}
#'
#' @export
chisqposthoc <- function(
    data,
    rows,
    cols,
    counts,
    stdres = FALSE,
    momcorrstdres = FALSE,
    adjstdres = TRUE,
    quetelet = FALSE,
    ij = FALSE,
    bsOutlier = FALSE,
    bsKmax = 2,
    pem = FALSE,
    medpolish = FALSE,
    adjmedpolish = FALSE,
    gkres = FALSE,
    dep = FALSE,
    depOutcome,
    sidakCorrection = FALSE,
    confLevel = 95,
    bootstrapReps = 999,
    seed = 123,
    showPemPlot = FALSE,
    pemPlotFilter = "all",
    showDepPlot = FALSE,
    showMethodInfo = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqposthoc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- chisqposthocOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        stdres = stdres,
        momcorrstdres = momcorrstdres,
        adjstdres = adjstdres,
        quetelet = quetelet,
        ij = ij,
        bsOutlier = bsOutlier,
        bsKmax = bsKmax,
        pem = pem,
        medpolish = medpolish,
        adjmedpolish = adjmedpolish,
        gkres = gkres,
        dep = dep,
        depOutcome = depOutcome,
        sidakCorrection = sidakCorrection,
        confLevel = confLevel,
        bootstrapReps = bootstrapReps,
        seed = seed,
        showPemPlot = showPemPlot,
        pemPlotFilter = pemPlotFilter,
        showDepPlot = showDepPlot,
        showMethodInfo = showMethodInfo)

    analysis <- chisqposthocClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

