
# This file is automatically generated, you probably don't want to edit this

chisqassocOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqassocOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            phi = FALSE,
            phiSigned = FALSE,
            phiCorrected = FALSE,
            coleC7 = FALSE,
            zysnoPhi = FALSE,
            contingencyC = FALSE,
            cAdjusted = FALSE,
            cCorrected = FALSE,
            cramersV = TRUE,
            vCorrected = FALSE,
            vStandardised = FALSE,
            vBiasCorrected = FALSE,
            cohenW = FALSE,
            wHat = FALSE,
            wHatCorrected = FALSE,
            sakoda = FALSE,
            sakodaCorrected = FALSE,
            sakodaLocal = FALSE,
            yulesQ = FALSE,
            yulesY = FALSE,
            oddsRatio = FALSE,
            rowRef = NULL,
            colRef = NULL,
            gkLambda = FALSE,
            gkLambdaCorrected = FALSE,
            gkTau = FALSE,
            confLevel = 0.95,
            bootstrapReps = 999,
            seed = 123,
            showChisqMax = FALSE,
            showStandardised = FALSE,
            showThresholds = FALSE,
            showMethodInfo = FALSE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqassoc",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"))
            private$..phi <- jmvcore::OptionBool$new(
                "phi",
                phi,
                default=FALSE)
            private$..phiSigned <- jmvcore::OptionBool$new(
                "phiSigned",
                phiSigned,
                default=FALSE)
            private$..phiCorrected <- jmvcore::OptionBool$new(
                "phiCorrected",
                phiCorrected,
                default=FALSE)
            private$..coleC7 <- jmvcore::OptionBool$new(
                "coleC7",
                coleC7,
                default=FALSE)
            private$..zysnoPhi <- jmvcore::OptionBool$new(
                "zysnoPhi",
                zysnoPhi,
                default=FALSE)
            private$..contingencyC <- jmvcore::OptionBool$new(
                "contingencyC",
                contingencyC,
                default=FALSE)
            private$..cAdjusted <- jmvcore::OptionBool$new(
                "cAdjusted",
                cAdjusted,
                default=FALSE)
            private$..cCorrected <- jmvcore::OptionBool$new(
                "cCorrected",
                cCorrected,
                default=FALSE)
            private$..cramersV <- jmvcore::OptionBool$new(
                "cramersV",
                cramersV,
                default=TRUE)
            private$..vCorrected <- jmvcore::OptionBool$new(
                "vCorrected",
                vCorrected,
                default=FALSE)
            private$..vStandardised <- jmvcore::OptionBool$new(
                "vStandardised",
                vStandardised,
                default=FALSE)
            private$..vBiasCorrected <- jmvcore::OptionBool$new(
                "vBiasCorrected",
                vBiasCorrected,
                default=FALSE)
            private$..cohenW <- jmvcore::OptionBool$new(
                "cohenW",
                cohenW,
                default=FALSE)
            private$..wHat <- jmvcore::OptionBool$new(
                "wHat",
                wHat,
                default=FALSE)
            private$..wHatCorrected <- jmvcore::OptionBool$new(
                "wHatCorrected",
                wHatCorrected,
                default=FALSE)
            private$..sakoda <- jmvcore::OptionBool$new(
                "sakoda",
                sakoda,
                default=FALSE)
            private$..sakodaCorrected <- jmvcore::OptionBool$new(
                "sakodaCorrected",
                sakodaCorrected,
                default=FALSE)
            private$..sakodaLocal <- jmvcore::OptionBool$new(
                "sakodaLocal",
                sakodaLocal,
                default=FALSE)
            private$..yulesQ <- jmvcore::OptionBool$new(
                "yulesQ",
                yulesQ,
                default=FALSE)
            private$..yulesY <- jmvcore::OptionBool$new(
                "yulesY",
                yulesY,
                default=FALSE)
            private$..oddsRatio <- jmvcore::OptionBool$new(
                "oddsRatio",
                oddsRatio,
                default=FALSE)
            private$..rowRef <- jmvcore::OptionLevel$new(
                "rowRef",
                rowRef,
                variable="(rows)")
            private$..colRef <- jmvcore::OptionLevel$new(
                "colRef",
                colRef,
                variable="(cols)")
            private$..gkLambda <- jmvcore::OptionBool$new(
                "gkLambda",
                gkLambda,
                default=FALSE)
            private$..gkLambdaCorrected <- jmvcore::OptionBool$new(
                "gkLambdaCorrected",
                gkLambdaCorrected,
                default=FALSE)
            private$..gkTau <- jmvcore::OptionBool$new(
                "gkTau",
                gkTau,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                min=0.5,
                max=0.999,
                default=0.95)
            private$..bootstrapReps <- jmvcore::OptionInteger$new(
                "bootstrapReps",
                bootstrapReps,
                min=100,
                max=10000,
                default=999)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                min=1,
                max=999999,
                default=123)
            private$..showChisqMax <- jmvcore::OptionBool$new(
                "showChisqMax",
                showChisqMax,
                default=FALSE)
            private$..showStandardised <- jmvcore::OptionBool$new(
                "showStandardised",
                showStandardised,
                default=FALSE)
            private$..showThresholds <- jmvcore::OptionBool$new(
                "showThresholds",
                showThresholds,
                default=FALSE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..phi)
            self$.addOption(private$..phiSigned)
            self$.addOption(private$..phiCorrected)
            self$.addOption(private$..coleC7)
            self$.addOption(private$..zysnoPhi)
            self$.addOption(private$..contingencyC)
            self$.addOption(private$..cAdjusted)
            self$.addOption(private$..cCorrected)
            self$.addOption(private$..cramersV)
            self$.addOption(private$..vCorrected)
            self$.addOption(private$..vStandardised)
            self$.addOption(private$..vBiasCorrected)
            self$.addOption(private$..cohenW)
            self$.addOption(private$..wHat)
            self$.addOption(private$..wHatCorrected)
            self$.addOption(private$..sakoda)
            self$.addOption(private$..sakodaCorrected)
            self$.addOption(private$..sakodaLocal)
            self$.addOption(private$..yulesQ)
            self$.addOption(private$..yulesY)
            self$.addOption(private$..oddsRatio)
            self$.addOption(private$..rowRef)
            self$.addOption(private$..colRef)
            self$.addOption(private$..gkLambda)
            self$.addOption(private$..gkLambdaCorrected)
            self$.addOption(private$..gkTau)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..bootstrapReps)
            self$.addOption(private$..seed)
            self$.addOption(private$..showChisqMax)
            self$.addOption(private$..showStandardised)
            self$.addOption(private$..showThresholds)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        phi = function() private$..phi$value,
        phiSigned = function() private$..phiSigned$value,
        phiCorrected = function() private$..phiCorrected$value,
        coleC7 = function() private$..coleC7$value,
        zysnoPhi = function() private$..zysnoPhi$value,
        contingencyC = function() private$..contingencyC$value,
        cAdjusted = function() private$..cAdjusted$value,
        cCorrected = function() private$..cCorrected$value,
        cramersV = function() private$..cramersV$value,
        vCorrected = function() private$..vCorrected$value,
        vStandardised = function() private$..vStandardised$value,
        vBiasCorrected = function() private$..vBiasCorrected$value,
        cohenW = function() private$..cohenW$value,
        wHat = function() private$..wHat$value,
        wHatCorrected = function() private$..wHatCorrected$value,
        sakoda = function() private$..sakoda$value,
        sakodaCorrected = function() private$..sakodaCorrected$value,
        sakodaLocal = function() private$..sakodaLocal$value,
        yulesQ = function() private$..yulesQ$value,
        yulesY = function() private$..yulesY$value,
        oddsRatio = function() private$..oddsRatio$value,
        rowRef = function() private$..rowRef$value,
        colRef = function() private$..colRef$value,
        gkLambda = function() private$..gkLambda$value,
        gkLambdaCorrected = function() private$..gkLambdaCorrected$value,
        gkTau = function() private$..gkTau$value,
        confLevel = function() private$..confLevel$value,
        bootstrapReps = function() private$..bootstrapReps$value,
        seed = function() private$..seed$value,
        showChisqMax = function() private$..showChisqMax$value,
        showStandardised = function() private$..showStandardised$value,
        showThresholds = function() private$..showThresholds$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..phi = NA,
        ..phiSigned = NA,
        ..phiCorrected = NA,
        ..coleC7 = NA,
        ..zysnoPhi = NA,
        ..contingencyC = NA,
        ..cAdjusted = NA,
        ..cCorrected = NA,
        ..cramersV = NA,
        ..vCorrected = NA,
        ..vStandardised = NA,
        ..vBiasCorrected = NA,
        ..cohenW = NA,
        ..wHat = NA,
        ..wHatCorrected = NA,
        ..sakoda = NA,
        ..sakodaCorrected = NA,
        ..sakodaLocal = NA,
        ..yulesQ = NA,
        ..yulesY = NA,
        ..oddsRatio = NA,
        ..rowRef = NA,
        ..colRef = NA,
        ..gkLambda = NA,
        ..gkLambdaCorrected = NA,
        ..gkTau = NA,
        ..confLevel = NA,
        ..bootstrapReps = NA,
        ..seed = NA,
        ..showChisqMax = NA,
        ..showStandardised = NA,
        ..showThresholds = NA,
        ..showMethodInfo = NA)
)

chisqassocResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqassocResults",
    inherit = jmvcore::Group,
    active = list(
        crosstabTable = function() private$.items[["crosstabTable"]],
        orInterpretation = function() private$.items[["orInterpretation"]],
        chisqMaxTable = function() private$.items[["chisqMaxTable"]],
        standardisedTable = function() private$.items[["standardisedTable"]],
        resultsTable = function() private$.items[["resultsTable"]],
        sakodaLocalTable = function() private$.items[["sakodaLocalTable"]],
        sakodaLocalNote = function() private$.items[["sakodaLocalNote"]],
        pairwiseTable = function() private$.items[["pairwiseTable"]],
        unilateralWarning = function() private$.items[["unilateralWarning"]],
        thresholdsTable = function() private$.items[["thresholdsTable"]],
        methodInfo = function() private$.items[["methodInfo"]],
        legendNote = function() private$.items[["legendNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measures of Association and Effect Sizes")
            self$add(jmvcore::Table$new(
                options=options,
                name="crosstabTable",
                title="Observed Contingency Table",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="orInterpretation",
                title="",
                visible="(oddsRatio)",
                clearWith=list(
                    "rows",
                    "cols",
                    "rowRef",
                    "colRef")))
            self$add(jmvcore::Table$new(
                options=options,
                name="chisqMaxTable",
                title="Chi-Square-Maximising Table",
                visible="(showChisqMax)",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="standardisedTable",
                title="Standardised Contingency Table",
                visible="(showStandardised)",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="resultsTable",
                title="Association Measures Summary",
                clearWith=list(
                    "rows",
                    "cols",
                    "confLevel",
                    "bootstrapReps",
                    "phi",
                    "phiSigned",
                    "phiCorrected",
                    "coleC7",
                    "zysnoPhi",
                    "contingencyC",
                    "cAdjusted",
                    "cCorrected",
                    "cramersV",
                    "vCorrected",
                    "vStandardised",
                    "vBiasCorrected",
                    "cohenW",
                    "wHat",
                    "wHatCorrected",
                    "sakoda",
                    "sakodaCorrected",
                    "yulesQ",
                    "yulesY",
                    "oddsRatio",
                    "rowRef",
                    "colRef",
                    "gkLambda",
                    "gkLambdaCorrected",
                    "gkTau"),
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="lowerCI", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upperCI", 
                        `title`="Upper CI", 
                        `type`="number"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="effectSize", 
                        `title`="Effect Size", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="sakodaLocalTable",
                title="Sakoda's D (Local) / PEM",
                visible="(sakodaLocal)",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="sakodaLocalNote",
                title="",
                visible="(sakodaLocal)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="pairwiseTable",
                title="Pairwise Comparisons",
                visible=FALSE,
                clearWith=list(
                    "rows",
                    "cols",
                    "confLevel",
                    "yulesQ",
                    "yulesY",
                    "oddsRatio"),
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="lowerCI", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upperCI", 
                        `title`="Upper CI", 
                        `type`="number"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="effectSize", 
                        `title`="Effect Size", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="unilateralWarning",
                title="",
                visible=FALSE,
                clearWith=list(
                    "rows",
                    "cols")))
            self$add(jmvcore::Table$new(
                options=options,
                name="thresholdsTable",
                title="Effect Size Interpretation Thresholds",
                visible="(showThresholds)",
                clearWith=list(
                    "rows",
                    "cols",
                    "phi",
                    "phiSigned",
                    "phiCorrected",
                    "contingencyC",
                    "cAdjusted",
                    "cCorrected",
                    "cramersV",
                    "vCorrected",
                    "vStandardised",
                    "vBiasCorrected",
                    "cohenW",
                    "wHat",
                    "wHatCorrected",
                    "sakoda",
                    "sakodaCorrected",
                    "sakodaLocal",
                    "yulesQ",
                    "yulesY",
                    "oddsRatio"),
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="small", 
                        `title`="Small", 
                        `type`="text"),
                    list(
                        `name`="medium", 
                        `title`="Medium", 
                        `type`="text"),
                    list(
                        `name`="large", 
                        `title`="Large", 
                        `type`="text"),
                    list(
                        `name`="notes", 
                        `title`="Notes", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "rows",
                    "cols",
                    "phi",
                    "phiSigned",
                    "phiCorrected",
                    "contingencyC",
                    "cAdjusted",
                    "cCorrected",
                    "cramersV",
                    "vCorrected",
                    "vStandardised",
                    "vBiasCorrected",
                    "cohenW",
                    "wHat",
                    "wHatCorrected",
                    "sakoda",
                    "sakodaCorrected",
                    "sakodaLocal",
                    "yulesQ",
                    "yulesY",
                    "oddsRatio",
                    "gkLambda",
                    "gkLambdaCorrected",
                    "gkTau")))
            self$add(jmvcore::Html$new(
                options=options,
                name="legendNote",
                title="References"))}))

chisqassocBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqassocBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqassoc",
                version = c(1,0,0),
                options = options,
                results = chisqassocResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Measures of Association and Effect Sizes
#'
#' Comprehensive measures of categorical association organised by statistical 
#' foundation.
#' 
#' Provides:
#' - Chi-square-based measures (Phi, Cramér's V, Cohen's w, W-hat, etc.)
#' - Margin-free measures (Yule's Q, Y, Odds Ratios)
#' - PRE measures (Goodman-Kruskal Lambda and Tau)
#' - Confidence intervals where available
#' - Effect size interpretation with table-specific thresholds
#' - Chi-square-maximising table
#' - Standardised contingency table
#' 
#' Effect sizes are assessed using Cohen (1988) thresholds adjusted for 
#' table size and maximum achievable values where applicable.
#' 
#'
#' @examples
#' # Example with Titanic data
#' data('Titanic')
#' titanic_df <- as.data.frame(Titanic)
#' titanic_expanded <- titanic_df[rep(seq_len(nrow(titanic_df)),
#'                                    titanic_df$Freq), 1:4]
#'
#' chisqassoc(
#'     data = titanic_expanded,
#'     rows = 'Class',
#'     cols = 'Survived',
#'     cramersV = TRUE,
#'     yulesQ = TRUE,
#'     gkLambda = TRUE
#' )
#'
#' @param data the data as a data frame
#' @param rows a string naming the variable for rows in the contingency table
#'   (must be a factor)
#' @param cols a string naming the variable for columns in the contingency
#'   table (must be a factor)
#' @param counts optional variable containing frequency counts for wide-format
#'   data. If not provided, data are assumed to be in long format (one row per
#'   case).
#' @param phi TRUE or FALSE (default), compute Phi coefficient for 2×2 tables
#' @param phiSigned TRUE or FALSE (default), compute signed Phi coefficient
#'   for 2×2 tables
#' @param phiCorrected TRUE or FALSE (default), compute corrected Phi
#'   coefficient for 2×2 tables
#' @param coleC7 TRUE or FALSE (default), compute Cole's C7 coefficient with
#'   Ratliff's (1982) correction for 2×2 tables. A margin-free measure that
#'   normalises the cross-product difference by its maximum achievable value
#'   given the marginals.
#' @param zysnoPhi TRUE or FALSE (default), compute Zysno's (1997) phi-star
#'   coefficient for 2×2 tables. A margin-free measure that reduces phi's
#'   dependence on marginal distributions while retaining sensitivity to
#'   association strength.
#' @param contingencyC TRUE or FALSE (default), compute contingency
#'   coefficient C
#' @param cAdjusted TRUE or FALSE (default), compute adjusted contingency
#'   coefficient C
#' @param cCorrected TRUE or FALSE (default), compute maximum-corrected
#'   contingency coefficient C
#' @param cramersV TRUE (default) or FALSE, compute Cramér's V with confidence
#'   interval
#' @param vCorrected TRUE or FALSE (default), compute maximum-corrected
#'   Cramér's V
#' @param vStandardised TRUE or FALSE (default), compute Cramér's V on
#'   standardised table
#' @param vBiasCorrected TRUE or FALSE (default), compute bias-corrected
#'   Cramér's V
#' @param cohenW TRUE or FALSE (default), compute Cohen's w
#' @param wHat TRUE or FALSE (default), compute W-hat coefficient with
#'   confidence interval
#' @param wHatCorrected TRUE or FALSE (default), compute maximum-corrected
#'   W-hat coefficient. Corrects for the maximum achievable value in tables with
#'   asymmetric marginals.
#' @param sakoda TRUE or FALSE (default), Sakoda's generalized index of
#'   dissimilarity (D_G), a global measure of association representing the
#'   proportion of cases needing redistribution to achieve independence.
#' @param sakodaCorrected TRUE or FALSE (default), compute maximum-corrected
#'   Sakoda's D Global. Corrects for the maximum achievable value in tables with
#'   asymmetric marginals.
#' @param sakodaLocal TRUE or FALSE (default), Sakoda's cell-level index of
#'   dissimilarity (D_ij), mathematically equivalent to Cibois's PEM (Percentage
#'   of Maximum deviation). Displays a table of local association values without
#'   confidence intervals. For bootstrap CIs, use the Post-hoc Analysis
#'   facility.
#' @param yulesQ TRUE or FALSE (default), compute Yule's Q with confidence
#'   interval and p-value. For 2×2 tables: single value. For larger tables:
#'   pairwise comparisons.
#' @param yulesY TRUE or FALSE (default), compute Yule's Y with confidence
#'   interval and p-value. For 2×2 tables: single value. For larger tables:
#'   pairwise comparisons.
#' @param oddsRatio TRUE or FALSE (default), compute Odds Ratio with
#'   confidence interval and p-value. For 2×2 tables: single value with optional
#'   interpretation based on reference categories. For larger tables:
#'   independent odds ratios.
#' @param rowRef The row level selected as the category of interest.
#' @param colRef The column level selected as the category of interest.
#' @param gkLambda TRUE or FALSE (default), compute Goodman-Kruskal Lambda
#'   (asymmetric and symmetric) with confidence intervals
#' @param gkLambdaCorrected TRUE or FALSE (default), compute corrected
#'   Goodman-Kruskal Lambda
#' @param gkTau TRUE or FALSE (default), compute Goodman-Kruskal Tau
#'   (asymmetric) with confidence interval
#' @param confLevel confidence level for confidence intervals (default: 0.95)
#' @param bootstrapReps number of bootstrap replications for computing
#'   confidence intervals. Applies to: Phi corrected, C adjusted, C corrected, V
#'   corrected, W-hat, W-hat corrected, Sakoda's D, and Sakoda's D corrected.
#'   Default: 999. See table annotation for details.
#' @param seed random seed for reproducibility (default: 123)
#' @param showChisqMax TRUE or FALSE (default), display the
#'   chi-square-maximising table
#' @param showStandardised TRUE or FALSE (default), display the standardised
#'   contingency table
#' @param showThresholds TRUE or FALSE (default), display effect size
#'   interpretation thresholds
#' @param showMethodInfo TRUE or FALSE (default), display detailed
#'   methodological explanations for selected measures
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$crosstabTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$orInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$chisqMaxTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$standardisedTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$resultsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sakodaLocalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sakodaLocalNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$pairwiseTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$unilateralWarning} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$thresholdsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$legendNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crosstabTable$asDF}
#'
#' \code{as.data.frame(results$crosstabTable)}
#'
#' @export
chisqassoc <- function(
    data,
    rows,
    cols,
    counts,
    phi = FALSE,
    phiSigned = FALSE,
    phiCorrected = FALSE,
    coleC7 = FALSE,
    zysnoPhi = FALSE,
    contingencyC = FALSE,
    cAdjusted = FALSE,
    cCorrected = FALSE,
    cramersV = TRUE,
    vCorrected = FALSE,
    vStandardised = FALSE,
    vBiasCorrected = FALSE,
    cohenW = FALSE,
    wHat = FALSE,
    wHatCorrected = FALSE,
    sakoda = FALSE,
    sakodaCorrected = FALSE,
    sakodaLocal = FALSE,
    yulesQ = FALSE,
    yulesY = FALSE,
    oddsRatio = FALSE,
    rowRef,
    colRef,
    gkLambda = FALSE,
    gkLambdaCorrected = FALSE,
    gkTau = FALSE,
    confLevel = 0.95,
    bootstrapReps = 999,
    seed = 123,
    showChisqMax = FALSE,
    showStandardised = FALSE,
    showThresholds = FALSE,
    showMethodInfo = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqassoc requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- chisqassocOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        phi = phi,
        phiSigned = phiSigned,
        phiCorrected = phiCorrected,
        coleC7 = coleC7,
        zysnoPhi = zysnoPhi,
        contingencyC = contingencyC,
        cAdjusted = cAdjusted,
        cCorrected = cCorrected,
        cramersV = cramersV,
        vCorrected = vCorrected,
        vStandardised = vStandardised,
        vBiasCorrected = vBiasCorrected,
        cohenW = cohenW,
        wHat = wHat,
        wHatCorrected = wHatCorrected,
        sakoda = sakoda,
        sakodaCorrected = sakodaCorrected,
        sakodaLocal = sakodaLocal,
        yulesQ = yulesQ,
        yulesY = yulesY,
        oddsRatio = oddsRatio,
        rowRef = rowRef,
        colRef = colRef,
        gkLambda = gkLambda,
        gkLambdaCorrected = gkLambdaCorrected,
        gkTau = gkTau,
        confLevel = confLevel,
        bootstrapReps = bootstrapReps,
        seed = seed,
        showChisqMax = showChisqMax,
        showStandardised = showStandardised,
        showThresholds = showThresholds,
        showMethodInfo = showMethodInfo)

    analysis <- chisqassocClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

