
# This file is automatically generated, you probably don't want to edit this

chisqclusterOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqclusterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            plotRowDendro = FALSE,
            plotColDendro = FALSE,
            showMethodInfo = FALSE,
            partitionMethod = "greenacre", ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqcluster",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"))
            private$..plotRowDendro <- jmvcore::OptionBool$new(
                "plotRowDendro",
                plotRowDendro,
                default=FALSE)
            private$..plotColDendro <- jmvcore::OptionBool$new(
                "plotColDendro",
                plotColDendro,
                default=FALSE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)
            private$..partitionMethod <- jmvcore::OptionList$new(
                "partitionMethod",
                partitionMethod,
                options=list(
                    "greenacre",
                    "inertia"),
                default="greenacre")

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..plotRowDendro)
            self$.addOption(private$..plotColDendro)
            self$.addOption(private$..showMethodInfo)
            self$.addOption(private$..partitionMethod)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        plotRowDendro = function() private$..plotRowDendro$value,
        plotColDendro = function() private$..plotColDendro$value,
        showMethodInfo = function() private$..showMethodInfo$value,
        partitionMethod = function() private$..partitionMethod$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..plotRowDendro = NA,
        ..plotColDendro = NA,
        ..showMethodInfo = NA,
        ..partitionMethod = NA)
)

chisqclusterResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqclusterResults",
    inherit = jmvcore::Group,
    active = list(
        crosstabTable = function() private$.items[["crosstabTable"]],
        rowClusterTable = function() private$.items[["rowClusterTable"]],
        rowGroupsTable = function() private$.items[["rowGroupsTable"]],
        rowDendro = function() private$.items[["rowDendro"]],
        colClusterTable = function() private$.items[["colClusterTable"]],
        colGroupsTable = function() private$.items[["colGroupsTable"]],
        colDendro = function() private$.items[["colDendro"]],
        methodInfo = function() private$.items[["methodInfo"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Contingency Table Row/Column Clustering")
            self$add(jmvcore::Table$new(
                options=options,
                name="crosstabTable",
                title="Observed Contingency Table",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowClusterTable",
                title="Row Merging Sequence",
                refs=list(
                    "greenacre1988",
                    "greenacre2017",
                    "hirotsu1983",
                    "hussonetal2017",
                    "pearsonhartley1972",
                    "ward1963"),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "partitionMethod"),
                columns=list(
                    list(
                        `name`="step", 
                        `title`="Step", 
                        `type`="integer"),
                    list(
                        `name`="itemsMerged", 
                        `title`="Items Merged", 
                        `type`="text"),
                    list(
                        `name`="groupsRemaining", 
                        `title`="Groups After Merge", 
                        `type`="text"),
                    list(
                        `name`="chiSquare", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="reduction", 
                        `title`="\u03C7\u00B2 Reduction", 
                        `type`="number"),
                    list(
                        `name`="reductionPercent", 
                        `title`="% Reduction", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="rowGroupsTable",
                title="Identified Row Groups",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "partitionMethod"),
                columns=list(
                    list(
                        `name`="groupName", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="members", 
                        `title`="Members", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="rowDendro",
                title="Row Clustering Dendrogram",
                visible="(plotRowDendro)",
                width=600,
                height=450,
                renderFun=".plotRowDendro",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "partitionMethod")))
            self$add(jmvcore::Table$new(
                options=options,
                name="colClusterTable",
                title="Column Merging Sequence",
                refs=list(
                    "greenacre1988",
                    "greenacre2017",
                    "hirotsu1983",
                    "hussonetal2017",
                    "pearsonhartley1972",
                    "ward1963"),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "partitionMethod"),
                columns=list(
                    list(
                        `name`="step", 
                        `title`="Step", 
                        `type`="integer"),
                    list(
                        `name`="itemsMerged", 
                        `title`="Items Merged", 
                        `type`="text"),
                    list(
                        `name`="groupsRemaining", 
                        `title`="Groups After Merge", 
                        `type`="text"),
                    list(
                        `name`="chiSquare", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="reduction", 
                        `title`="\u03C7\u00B2 Reduction", 
                        `type`="number"),
                    list(
                        `name`="reductionPercent", 
                        `title`="% Reduction", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="colGroupsTable",
                title="Identified Column Groups",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "partitionMethod"),
                columns=list(
                    list(
                        `name`="groupName", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="members", 
                        `title`="Members", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="colDendro",
                title="Column Clustering Dendrogram",
                visible="(plotColDendro)",
                width=600,
                height=450,
                renderFun=".plotColDendro",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "partitionMethod")))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "rows",
                    "cols")))}))

chisqclusterBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqclusterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqcluster",
                version = c(1,0,0),
                options = options,
                results = chisqclusterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Contingency Table Row/Column Clustering
#'
#' Hierarchical clustering analysis for contingency table rows and columns 
#' using the Greenacre (2017) method.
#' 
#' Provides:
#' - Agglomerative clustering with Ward linkage criterion
#' - Critical chi-square values for optimal cluster identification
#' - Cluster dendrograms with significance cutoff lines
#' - Detailed merging sequence statistics
#' - Identified significant row and column groups
#' 
#' The method uses chi-square distance to identify homogeneous groups of rows 
#' (or columns) that can be merged without significantly reducing the table's 
#' association. Merging continues until the chi-square statistic falls below 
#' a critical threshold adjusted for multiple comparisons (Greenacre 2017, 
#' Exhibit A.1, p.254).
#' 
#'
#' @examples
#' # Example with contingency table
#' data <- data.frame(
#'   "16-24" = c(37, 13, 33, 16, 8),
#'   "25-34" = c(39, 23, 69, 31, 16),
#'   "35-49" = c(45, 33, 67, 34, 21),
#'   "50+" = c(64, 38, 56, 22, 35)
#' )
#' rownames(data) <- c("A", "B", "C", "D", "E")
#'
#' chisqcluster(
#'     data = data,
#'     rows = 'Category',
#'     cols = 'AgeGroup',
#'     plotRowDendro = TRUE,
#'     plotColDendro = TRUE
#' )
#'
#' @param data the data as a data frame
#' @param rows a string naming the variable for rows in the contingency table
#'   (must be a factor)
#' @param cols a string naming the variable for columns in the contingency
#'   table (must be a factor)
#' @param counts optional variable containing frequency counts for wide-format
#'   data. If not provided, data are assumed to be in long format (one row per
#'   case).
#' @param plotRowDendro TRUE or FALSE (default), display hierarchical
#'   clustering dendrogram  for table rows with critical value cutoff line
#' @param plotColDendro TRUE or FALSE (default), display hierarchical
#'   clustering dendrogram  for table columns with critical value cutoff line
#' @param showMethodInfo TRUE or FALSE (default), display detailed
#'   methodological  explanations for the clustering procedure
#' @param partitionMethod Method for selecting the optimal partition.
#'   'greenacre' uses  critical chi-square values from Pearson & Hartley (1972)
#'   to  identify statistically significant groupings. 'inertia' uses  the
#'   relative drop in between-cluster inertia gain to find  the "elbow" in the
#'   clustering hierarchy (Husson et al., 2017).
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$crosstabTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowClusterTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowGroupsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rowDendro} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$colClusterTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colGroupsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$colDendro} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crosstabTable$asDF}
#'
#' \code{as.data.frame(results$crosstabTable)}
#'
#' @export
chisqcluster <- function(
    data,
    rows,
    cols,
    counts,
    plotRowDendro = FALSE,
    plotColDendro = FALSE,
    showMethodInfo = FALSE,
    partitionMethod = "greenacre") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqcluster requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- chisqclusterOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        plotRowDendro = plotRowDendro,
        plotColDendro = plotColDendro,
        showMethodInfo = showMethodInfo,
        partitionMethod = partitionMethod)

    analysis <- chisqclusterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

