
# This file is automatically generated, you probably don't want to edit this

chisqtestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqtestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            traditionalTest = TRUE,
            n1Test = FALSE,
            permTest = FALSE,
            monteCarloTest = FALSE,
            mTest = FALSE,
            nPerms = 999,
            seed = 123,
            showDistributions = FALSE,
            showMethodInfo = FALSE, ...) {

            super$initialize(
                package="ChiSquaredTools",
                name="chisqtest",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"))
            private$..traditionalTest <- jmvcore::OptionBool$new(
                "traditionalTest",
                traditionalTest,
                default=TRUE)
            private$..n1Test <- jmvcore::OptionBool$new(
                "n1Test",
                n1Test,
                default=FALSE)
            private$..permTest <- jmvcore::OptionBool$new(
                "permTest",
                permTest,
                default=FALSE)
            private$..monteCarloTest <- jmvcore::OptionBool$new(
                "monteCarloTest",
                monteCarloTest,
                default=FALSE)
            private$..mTest <- jmvcore::OptionBool$new(
                "mTest",
                mTest,
                default=FALSE)
            private$..nPerms <- jmvcore::OptionInteger$new(
                "nPerms",
                nPerms,
                min=99,
                max=9999,
                default=999)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                min=1,
                max=999999,
                default=123)
            private$..showDistributions <- jmvcore::OptionBool$new(
                "showDistributions",
                showDistributions,
                default=FALSE)
            private$..showMethodInfo <- jmvcore::OptionBool$new(
                "showMethodInfo",
                showMethodInfo,
                default=FALSE)

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..traditionalTest)
            self$.addOption(private$..n1Test)
            self$.addOption(private$..permTest)
            self$.addOption(private$..monteCarloTest)
            self$.addOption(private$..mTest)
            self$.addOption(private$..nPerms)
            self$.addOption(private$..seed)
            self$.addOption(private$..showDistributions)
            self$.addOption(private$..showMethodInfo)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        traditionalTest = function() private$..traditionalTest$value,
        n1Test = function() private$..n1Test$value,
        permTest = function() private$..permTest$value,
        monteCarloTest = function() private$..monteCarloTest$value,
        mTest = function() private$..mTest$value,
        nPerms = function() private$..nPerms$value,
        seed = function() private$..seed$value,
        showDistributions = function() private$..showDistributions$value,
        showMethodInfo = function() private$..showMethodInfo$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..traditionalTest = NA,
        ..n1Test = NA,
        ..permTest = NA,
        ..monteCarloTest = NA,
        ..mTest = NA,
        ..nPerms = NA,
        ..seed = NA,
        ..showDistributions = NA,
        ..showMethodInfo = NA)
)

chisqtestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqtestResults",
    inherit = jmvcore::Group,
    active = list(
        crosstabTable = function() private$.items[["crosstabTable"]],
        expectedTable = function() private$.items[["expectedTable"]],
        tableCharacteristics = function() private$.items[["tableCharacteristics"]],
        validityAssessment = function() private$.items[["validityAssessment"]],
        testResults = function() private$.items[["testResults"]],
        permDistPlot = function() private$.items[["permDistPlot"]],
        mcDistPlot = function() private$.items[["mcDistPlot"]],
        methodInfo = function() private$.items[["methodInfo"]],
        legendNote = function() private$.items[["legendNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Chi-Squared Test of Independence")
            self$add(jmvcore::Table$new(
                options=options,
                name="crosstabTable",
                title="Observed Contingency Table",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="expectedTable",
                title="Expected Frequencies",
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableCharacteristics",
                title="Table Characteristics",
                rows=0,
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list(
                    list(
                        `name`="characteristic", 
                        `title`="Characteristic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text")),
                refs=list(
                    "alberti2024",
                    "rhoades1982",
                    "roscoe1971",
                    "zar2014")))
            self$add(jmvcore::Table$new(
                options=options,
                name="validityAssessment",
                title="Test Validity Assessment",
                rows=0,
                clearWith=list(
                    "rows",
                    "cols"),
                columns=list(
                    list(
                        `name`="diagnostic", 
                        `title`="Diagnostic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"),
                    list(
                        `name`="threshold", 
                        `title`="Threshold", 
                        `type`="text"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text")),
                refs=list(
                    "alberti2024",
                    "koehler1980",
                    "roscoe1971",
                    "zar2014")))
            self$add(jmvcore::Table$new(
                options=options,
                name="testResults",
                title="Test Results",
                clearWith=list(
                    "rows",
                    "cols",
                    "nPerms",
                    "seed"),
                columns=list(
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="mstat", 
                        `title`="M", 
                        `type`="number"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                refs=list(
                    "alberti2024",
                    "campbell2007",
                    "fuchs1980",
                    "lin2015")))
            self$add(jmvcore::Image$new(
                options=options,
                name="permDistPlot",
                title="Permutation Test Distribution",
                visible="(showDistributions && permTest)",
                width=500,
                height=400,
                renderFun=".plotPermDist",
                clearWith=list(
                    "rows",
                    "cols",
                    "nPerms",
                    "seed")))
            self$add(jmvcore::Image$new(
                options=options,
                name="mcDistPlot",
                title="Monte Carlo Test Distribution",
                visible="(showDistributions && monteCarloTest)",
                width=500,
                height=400,
                renderFun=".plotMCDist",
                clearWith=list(
                    "rows",
                    "cols",
                    "nPerms",
                    "seed")))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodInfo",
                title="Method Details",
                visible="(showMethodInfo)",
                clearWith=list(
                    "rows",
                    "cols",
                    "traditionalTest",
                    "n1Test",
                    "permTest",
                    "monteCarloTest")))
            self$add(jmvcore::Html$new(
                options=options,
                name="legendNote",
                title="References"))}))

chisqtestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chisqtestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ChiSquaredTools",
                name = "chisqtest",
                version = c(1,0,0),
                options = options,
                results = chisqtestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Chi-Squared Test of Independence
#'
#' Chi-squared test of independence with multiple testing methods:
#' - Traditional chi-squared test
#' - (N-1) adjusted chi-squared test
#' - Permutation-based test
#' - Monte Carlo test (with Phipson & Smyth 2010 p-value computation)
#' 
#' Includes method selection guidance based on table characteristics,
#' optional distribution plots, and comprehensive method annotations.
#' 
#'
#' @examples
#' # Example with Titanic data
#' data('Titanic')
#' titanic_df <- as.data.frame(Titanic)
#' titanic_expanded <- titanic_df[rep(seq_len(nrow(titanic_df)),
#'                                    titanic_df$Freq), 1:4]
#'
#' chisqtest(
#'     data = titanic_expanded,
#'     rows = 'Class',
#'     cols = 'Survived',
#'     traditionalTest = TRUE,
#'     n1Test = TRUE,
#'     permTest = TRUE,
#'     monteCarloTest = TRUE
#' )
#'
#' @param data the data as a data frame
#' @param rows a string naming the variable for rows in the contingency table
#'   (must be a factor)
#' @param cols a string naming the variable for columns in the contingency
#'   table (must be a factor)
#' @param counts optional variable containing frequency counts for wide-format
#'   data. If not provided, data are assumed to be in long format (one row per
#'   case).
#' @param traditionalTest TRUE or FALSE (default: TRUE), compute traditional
#'   chi-squared test
#' @param n1Test TRUE or FALSE (default: FALSE), compute (N-1)/N adjusted
#'   chi-squared test
#' @param permTest TRUE or FALSE (default: FALSE), compute permutation-based
#'   test
#' @param monteCarloTest TRUE or FALSE (default: FALSE), compute Monte Carlo
#'   test
#' @param mTest TRUE or FALSE (default: FALSE), compute M test based on
#'   maximum adjusted residual (Fuchs & Kenett, 1980). Uses Bonferroni
#'   correction for multiple comparisons. May have higher power than chi-squared
#'   when association is driven by a single outlying cell.
#' @param nPerms number of permutations or Monte Carlo replications (default:
#'   999)
#' @param seed random seed for reproducibility (default: 123)
#' @param showDistributions TRUE or FALSE (default: FALSE), plot distributions
#'   of permutation and Monte Carlo test statistics
#' @param showMethodInfo TRUE or FALSE (default: FALSE), display detailed
#'   methodological  explanations for all selected tests
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$crosstabTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$expectedTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tableCharacteristics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$validityAssessment} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$testResults} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$permDistPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mcDistPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodInfo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$legendNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crosstabTable$asDF}
#'
#' \code{as.data.frame(results$crosstabTable)}
#'
#' @export
chisqtest <- function(
    data,
    rows,
    cols,
    counts,
    traditionalTest = TRUE,
    n1Test = FALSE,
    permTest = FALSE,
    monteCarloTest = FALSE,
    mTest = FALSE,
    nPerms = 999,
    seed = 123,
    showDistributions = FALSE,
    showMethodInfo = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chisqtest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- chisqtestOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        traditionalTest = traditionalTest,
        n1Test = n1Test,
        permTest = permTest,
        monteCarloTest = monteCarloTest,
        mTest = mTest,
        nPerms = nPerms,
        seed = seed,
        showDistributions = showDistributions,
        showMethodInfo = showMethodInfo)

    analysis <- chisqtestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

